import { Quirk, Pitch } from "@prisma/client";

export interface ApiPlayer {
  uuid: string;
  name: string;
  rarity: string;
  team: string;
  team_short_name: string;
  ovr: number | null;
  age: number | null;
  height: string | null;
  weight: string;
  born: string | null;
  display_position: string | null;
  display_secondary_positions: string | null;
  series_year: number | null;
  baked_img: string | null;
  img: string | null;
  bat_hand: string | null;
  throw_hand: string | null;
  is_hitter: boolean;
  contact_left: number | null;
  contact_right: number | null;
  power_left: number | null;
  power_right: number | null;
  plate_vision: number | null;
  plate_discipline: number | null;
  batting_clutch: number | null;
  bunting_ability: number | null;
  drag_bunting_ability: number | null;
  hitting_durability: number | null;
  fielding_ability: number | null;
  arm_strength: number | null;
  arm_accuracy: number | null;
  reaction_time: number | null;
  blocking: number | null;
  speed: number | null;
  baserunning_ability: number | null;
  baserunning_aggression: number | null;
  stamina?: number | null;
  pitching_clutch?: number | null;
  hits_per_bf?: number | null;
  k_per_bf?: number | null;
  bb_per_bf?: number | null;
  hr_per_bf?: number | null;
  pitch_velocity?: number | null;
  pitch_control?: number | null;
  pitch_movement?: number | null;
  pitches?: {
    name: string;
    speed: number;
    control: number;
    movement: number;
  }[];
  quirks?: { name: string; description: string; img: string }[];
}
export interface ItemOverview {
  name: string;
  rarity: string;
  ovr: number;
  team: string;
  age: number;
  batHand: string;
  throwHand: string;
  display_position: string;
  display_secondary_positions: string;
}
export interface ItemObject {
  uuid: string;
  name: string;
  rarity: string;
  team: string;
  ovr: number;
  age: number;
  batHand: string;
  throwHand: string;
  isHitter: boolean;
  contactLeft: number;
  contactRight: number;
  powerLeft: number;
  powerRight: number;
  plateVision: number;
  plateDiscipline: number;
  battingClutch: number;
  buntingAbility: number;
  dragBuntingAbility: number;
  hittingDurability: number;
  fieldingAbility: number;
  armStrength: number;
  armAccuracy: number;
  reactionTime: number;
  blocking: number;
  speed: number;
  baserunningAbility: number;
  baserunningAggression: number;
  stamina?: number;
  pitchingClutch?: number;
  hitsPerBf?: number;
  kPerBf?: number;
  bbPerBf?: number;
  hrPerBf?: number;
  pitchVelocity?: number;
  pitchControl?: number;
  pitchMovement?: number;
  quirks?: Quirk[];
}
export type Player = {
  uuid: string;
  name: string;
  rarity: string;
  team: string;
  ovr: number;
  age: number;
  batHand: string;
  throwHand: string;
  isHitter: boolean;
  contactLeft: number;
  contactRight: number;
  powerLeft: number;
  powerRight: number;
  plateVision: number;
  plateDiscipline: number;
  battingClutch: number;
  buntingAbility: number;
  dragBuntingAbility: number;
  hittingDurability: number;
  fieldingAbility: number;
  armStrength: number;
  armAccuracy: number;
  reactionTime: number;
  blocking: number;
  speed: number;
  baserunningAbility: number;
  baserunningAggression: number;
  stamina?: number;
  pitchingClutch?: number;
  hitsPerBf?: number;
  kPerBf?: number;
  bbPerBf?: number;
  hrPerBf?: number;
  pitchVelocity?: number;
  pitchControl?: number;
  pitchMovement?: number;
  quirks?: Quirk[];
};
